version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: athos_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]

  web:
    build: .
    image: athos_app_image:latest
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - db
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  locust:
    image: locustio/locust:2.32.0
    ports:
      - "8089:8089"
    volumes:
      - .:/mnt/locust
    command: ["-f", "/mnt/locust/tests/locustfile.py", "--host", "http://web:5000", "--web-host", "0.0.0.0"]
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M

volumes:
  db_data:
